name: Publish Docker Image

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Create name for Docker image
        run: echo "IMAGE_NAME=${{ github.repository }}" >> $GITHUB_ENV
      - name: Find download URL
        run: echo "DOWNLOAD_URL=$(curl -SL "${{ github.event.release.url }}" | jq -r '.assets[] | select(.name == "docker.tar.bz2") | .browser_download_url')" >> $GITHUB_ENV
      - name: Download the saved Docker image
        run: curl -SLO "${DOWNLOAD_URL}"
      - name: Load Docker Image
        run: bunzip2 --stdout docker.tar.bz2 | docker image load
      - name: Login to Docker Hub
        run: docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_TOKEN}"
        env:
          DOCKER_USERNAME: mortenlj
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker Image
        run: docker push "${IMAGE_NAME}"
